CREATE TABLE TWEETS
(
  ID INT NOT NULL,
  Text VARCHAR(150) NOT NULL,
  Handle VARCHAR(25) NOT NULL,
  "Time" TIMESTAMP NOT NULL,
  Retweet_count INT,
  Favorite_count INT,
  Original_author VARCHAR(25),
  PRIMARY KEY (ID)
)

CREATE TABLE HASHTAGS
(
  ID INT NOT NULL,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (Name)
)

CREATE TABLE ENTHALTEN
(
  TweetID INT NOT NULL,
  HashtagID INT NOT NULL,
  mentioned_with INT,
  FOREIGN KEY (HashtagID) REFERENCES HASHTAGS (ID),
  FOREIGN KEY (TweetID) REFERENCES TWEETS (ID)
)
